name: run test cases
on: [pull_request, push]
jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt || true
      - run: python manage.py test
      - run: pip install coverage
      - run: coverage run ./manage.py test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
