name: run test cases
on: [pull_request, push]
jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: actions/checkout@v3
      - run: pip3 install virtualenv
      - run: mkdir packTravel
      - run: cd packTravel
      - run: virtualenv newenv
      - run: source newenv/bin/activate
      - run: pip3 install -r requirements.txt
      - run: pip3 install django
      - run: pip3 install django-allauth
      - run: pip3 install pymongo
      - run: python3 manage.py test
      - run: pip3 install coverage
      - run: coverage run ./manage.py test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
